// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAekA6gMrpZULYSECd6c69rts5NZgR5nAM',
    appId: '1:423725335419:web:1f022a86247df6fb0f73de',
    messagingSenderId: '423725335419',
    projectId: 'flutter-skeleton-23c23',
    authDomain: 'flutter-skeleton-23c23.firebaseapp.com',
    storageBucket: 'flutter-skeleton-23c23.appspot.com',
    measurementId: 'G-6NFJ6QH50J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bRqDiBPcKSggoEbdsLzs11Bu7p1xum0',
    appId: '1:423725335419:android:efa60ca0d2f6d81b0f73de',
    messagingSenderId: '423725335419',
    projectId: 'flutter-skeleton-23c23',
    storageBucket: 'flutter-skeleton-23c23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPwJ1tojS7Su0cUhvOwx_hsIFKEFUPyc',
    appId: '1:423725335419:ios:735cdf1e385ebac00f73de',
    messagingSenderId: '423725335419',
    projectId: 'flutter-skeleton-23c23',
    storageBucket: 'flutter-skeleton-23c23.appspot.com',
    iosClientId: '423725335419-g03an22li97nav3a1ahq3360m2ku0r54.apps.googleusercontent.com',
    iosBundleId: 'com.example.skeleton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPwJ1tojS7Su0cUhvOwx_hsIFKEFUPyc',
    appId: '1:423725335419:ios:735cdf1e385ebac00f73de',
    messagingSenderId: '423725335419',
    projectId: 'flutter-skeleton-23c23',
    storageBucket: 'flutter-skeleton-23c23.appspot.com',
    iosClientId: '423725335419-g03an22li97nav3a1ahq3360m2ku0r54.apps.googleusercontent.com',
    iosBundleId: 'com.example.skeleton',
  );
}
